### ISSUE TITLE
calling gsub! is a bug!

### ISSUE THREAD

**Issue by techieshark** [codeforamerica/CutePetsDenver#21]
I think the call to `gsub!` in `lib/extensions/string.rb` is causing unexpected (and buggy) behavior. 

We should remove the exclamation mark (!) from line nine (9) of lib/extensions/string.rb.

I could say more later, but in short, when the `remove_double_whitespace` method calls `gsub!` to try to replace multiple whitespace characters with a single space, but if the input string is already clean (doesn't have double whitespace), `gsub!` finds nothing to match and returns nil (rather than the original unaltered string, which is apparently what the code needs in order to work).  For more, see the [`gsub!` documentation](http://www.ruby-doc.org/core-2.1.1/String.html#method-i-gsub-21).

To reproduce, set the url to 'http://adopt-a-pet-mesa.herokuapp.com/api'

Here's the buggy output I was seeing:

```
Selene:cuties peter$ rake
rake aborted!
NoMethodError: undefined method `slice' for nil:NilClass
/Users/peter/Dropbox (Personal)/cfa/mesa/cuties/lib/cuties_in_denver/twit.rb:15:in `message'
/Users/peter/Dropbox (Personal)/cfa/mesa/cuties/lib/cuties_in_denver/twit.rb:31:in `block in tweet'
/Users/peter/Dropbox (Personal)/cfa/mesa/cuties/lib/cuties_in_denver/twit.rb:28:in `open'
/Users/peter/Dropbox (Personal)/cfa/mesa/cuties/lib/cuties_in_denver/twit.rb:28:in `tweet'
/Users/peter/Dropbox (Personal)/cfa/mesa/cuties/Rakefile:8:in `block in <top (required)>'
Tasks: TOP => default => twitter
```

**Comment by boonrs** [comment]
This issue has been resolved by using a nokogiri instead of rolling our own html parsing library.
