### ISSUE TITLE
Cuties on Heroku

### ISSUE THREAD

**Issue by lynnaloo** [codeforamerica/CutePetsDenver#25]
Hey guys, I posted this issue in the CutiesInBoston repo, but maybe you can help:

https://github.com/codeforboston/CutiesInBoston/issues/17

**Comment by boonrs** [comment]
Hi Lynn.  The template.env file is a relic of how we used to do things. I've created an issue to remove it. We set environment variables in heroku via `heroku config:set consumer_key=xxxxx`

This post goes into it in more detail: https://devcenter.heroku.com/articles/config-vars.

Let me know if you need additional details.

**Comment by lynnaloo** [comment]
I've gotten used to having a "sample.env", so I continued doing it that way out of routine for local development. As far as Heroku goes, I'm setting the configs just like you are. What about in your scheduler, are you just running "rake tweet" or are you adding configs there as well?

**Comment by boonrs** [comment]
We're using **Heroku Scheduler** with just `rake` as the task, no injection of environment variables.

**Comment by boonrs** [comment]
Per https://github.com/codeforboston/CutiesInBoston/issues/17 issue: "The problem was that in Heroku I had put single quotes around the shelter_id value and it was causing an error when it did the request."
